name: MihaelaDinu
favicon: null
layout_spectrum: 0.6308628935366869
typography_spectrum: 0.49731009383685887
title: MihaelaDinu
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.875
  lightness: 0.9698287844657898
  saturation: 0.5
  rhythmicContrast: 0.9528963973280042
purpose: []
